stages:
  - warm
  - jobs
variables:
  DAGGER_MODULE: github.com/ginjiruu/moodle_plugin_ci/pluginci

.dagger:
  tags:
    - dagger

.nodb-job:
  extends: [.dagger]
  variables:
    MOODLE_VERSION: MOODLE_401_STABLE
  parallel:
    matrix:
      - PHP_VERSION:
        - "7.4"
        - "8.0"
        - "8.1"
        DATABASE:
        - mariadb
.db-job:
  extends: [.dagger]
  variables:
    MOODLE_VERSION: MOODLE_401_STABLE
  parallel:
    matrix:
      - PHP_VERSION:
        - "7.4"
        - "8.0"
        - "8.1"
        DATABASE:
        - pgsql
        - mariadb


# Warm up configuration by installing all tested variations
warm:
  extends: [.db-job]
  stage: warm
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call moodle

# jobs that finish quickly
phplint:
  extends: [.nodb-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="phplint"
phpmd:
  extends: [.nodb-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="phpmd"
phpcs:
  extends: [.nodb-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="phpcs"
phpdoc:
  extends: [.nodb-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="phpdoc"
validate:
  extends: [.nodb-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="validate"
savepoints:
  extends: [.nodb-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="savepoints"

# jobs that take a while to finish
mustache:
  extends: [.db-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="mustache"
grunt:
  extends: [.db-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="grunt"
phpunit:
  extends: [.db-job]
  stage: jobs
  script:
    - dagger -m "$DAGGER_MODULE" --plugin=./ call test --operations="phpunit"
